import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/features/auth/auth-context";
import { TooltipProvider } from "@/components/ui/tooltip"
import { getMembershipForUser } from "@/lib/supabase/membership";
import { createClient } from "@/lib/supabase/server";
import { Toaster } from "sonner";
import { AppThemeProvider } from "@/components/theme-provider";
import { ReactQueryProvider } from "@/components/react-query-provider";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  let initialOrganizationId: string | null = null;
  let initialOrganizationName: string | null = null;
  let initialRole: string | null = null;
  if (user) {
    const membership = await getMembershipForUser(supabase, user.id);
    initialOrganizationId = membership?.organization_id ?? null;
    initialOrganizationName = membership?.organizationName ?? null;
    initialRole = membership?.role ?? null;
  }

  return (
    <html
      lang="en"
      className={cn("font-sans", inter.variable, "dark")}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TooltipProvider>
          <AppThemeProvider>
            <AuthProvider
              initialUser={user}
              initialOrganizationId={initialOrganizationId}
              initialOrganizationName={initialOrganizationName}
              initialRole={initialRole}
            >
              <ReactQueryProvider>{children}</ReactQueryProvider>
              <Toaster richColors closeButton />
            </AuthProvider>
          </AppThemeProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
